var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "hovermode": "closest", 
        "breakpoints": []
    }, 
    "data": [
        {
            "labelssrc": "aircar:12:d11fe5", 
            "autobinx": true, 
            "autobiny": true, 
            "labels": [
                "Location", 
                "District of Columbia", 
                "Wyoming", 
                "North Dakota", 
                "Vermont", 
                "Delaware", 
                "South Dakota", 
                "Rhode Island", 
                "Montana", 
                "New Hampshire", 
                "Maine", 
                "Idaho", 
                "Nebraska", 
                "West Virginia", 
                "Utah", 
                "New Mexico", 
                "Nevada", 
                "Mississippi", 
                "Iowa", 
                "Kansas", 
                "Arkansas", 
                "Connecticut", 
                "Oklahoma", 
                "Louisiana", 
                "South Carolina", 
                "Oregon", 
                "Alabama", 
                "Kentucky", 
                "Maryland", 
                "Minnesota", 
                "Colorado", 
                "Massachusetts", 
                "Wisconsin", 
                "Indiana", 
                "Arizona", 
                "Missouri", 
                "Tennessee", 
                "Virginia", 
                "New Jersey", 
                "Washington", 
                "North Carolina", 
                "Georgia", 
                "Michigan", 
                "Illinois", 
                "Ohio", 
                "Pennsylvania", 
                "New York", 
                "Florida", 
                "Texas", 
                "California"
            ], 
            "values": [
                "Number of Pet Households (in 1000)", 
                "63.00", 
                "137.00", 
                "147.00", 
                "188.00", 
                "189.00", 
                "219.00", 
                "230.00", 
                "251.00", 
                "289.00", 
                "345.00", 
                "352.00", 
                "364.00", 
                "475.00", 
                "476.00", 
                "523.00", 
                "548.00", 
                "629.00", 
                "654.00", 
                "691.00", 
                "716.00", 
                "728.00", 
                "872.00", 
                "937.00", 
                "951.00", 
                "957.00", 
                "1088.00", 
                "1094.00", 
                "1134.00", 
                "1146.00", 
                "1217.00", 
                "1318.00", 
                "1352.00", 
                "1484.00", 
                "1497.00", 
                "1534.00", 
                "1540.00", 
                "1611.00", 
                "1611.00", 
                "1649.00", 
                "2089.00", 
                "2093.00", 
                "2108.00", 
                "2602.00", 
                "2677.00", 
                "2942.00", 
                "3802.00", 
                "4138.00", 
                "5265.00", 
                "6865.00"
            ], 
            "mode": "markers", 
            "uid": "b3affa", 
            "type": "pie", 
            "valuessrc": "aircar:12:31ace1", 
            "name": "Column 1"
        }
    ]
}