var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "boxmode": "group", 
        "yaxis": {
            "range": [
                0, 
                7540
            ], 
            "type": "linear", 
            "autorange": true, 
            "title": "Pet Population (in 1000)"
        }, 
        "title": "Pet Population Comparison", 
        "showlegend": true, 
        "breakpoints": [], 
        "barmode": "group", 
        "xaxis": {
            "range": [
                -0.5, 
                49.5
            ], 
            "type": "category", 
            "autorange": true, 
            "title": "Location"
        }, 
        "hovermode": "x", 
        "legend": {
            "y": 1, 
            "x": 0.87, 
            "font": {
                "family": "Open Sans"
            }, 
            "orientation": "v", 
            "traceorder": "normal"
        }
    }, 
    "data": [
        {
            "autobinx": true, 
            "uid": "dba853", 
            "ysrc": "aircar:9:8bac20", 
            "xsrc": "aircar:9:633605", 
            "name": "Dog (Click me to Hide)", 
            "visible": true, 
            "transforms": [], 
            "y": [
                "Dog Population (in 1000)", 
                "7163.00", 
                "6687.00", 
                "4210.00", 
                "3054.00", 
                "2730.00", 
                "2518.00", 
                "2485.00", 
                "2479.00", 
                "2365.00", 
                "2157.00", 
                "2036.00", 
                "1978.00", 
                "1798.00", 
                "1699.00", 
                "1619.00", 
                "1609.00", 
                "1531.00", 
                "1410.00", 
                "1349.00", 
                "1340.00", 
                "1327.00", 
                "1191.00", 
                "1138.00", 
                "1115.00", 
                "1097.00", 
                "934.00", 
                "917.00", 
                "915.00", 
                "850.00", 
                "846.00", 
                "774.00", 
                "703.00", 
                "648.00", 
                "610.00", 
                "578.00", 
                "507.00", 
                "410.00", 
                "374.00", 
                "357.00", 
                "300.00", 
                "282.00", 
                "220.00", 
                "212.00", 
                "163.00", 
                "161.00", 
                "142.00", 
                "139.00", 
                "125.00", 
                "42.00"
            ], 
            "x": [
                "Location", 
                "Texas", 
                "California", 
                "Florida", 
                "New York", 
                "Ohio", 
                "North Carolina", 
                "Pennsylvania", 
                "Georgia", 
                "Illinois", 
                "Tennessee", 
                "Michigan", 
                "Missouri", 
                "Arizona", 
                "Virginia", 
                "Indiana", 
                "Washington", 
                "Kentucky", 
                "Alabama", 
                "Colorado", 
                "New Jersey", 
                "Oklahoma", 
                "South Carolina", 
                "Wisconsin", 
                "Louisiana", 
                "Arkansas", 
                "Minnesota", 
                "Oregon", 
                "Maryland", 
                "Massachusetts", 
                "Mississippi", 
                "Kansas", 
                "New Mexico", 
                "West Virginia", 
                "Iowa", 
                "Nevada", 
                "Connecticut", 
                "Utah", 
                "Nebraska", 
                "Idaho", 
                "Maine", 
                "Montana", 
                "South Dakota", 
                "New Hampshire", 
                "Delaware", 
                "Rhode Island", 
                "Vermont", 
                "North Dakota", 
                "Wyoming", 
                "District of Columbia"
            ], 
            "autobiny": true, 
            "type": "bar", 
            "mode": "markers"
        }, 
        {
            "opacity": 1, 
            "autobinx": true, 
            "uid": "fc9809", 
            "ysrc": "aircar:9:36dcfe", 
            "xsrc": "aircar:9:633605", 
            "name": "Cat (Click me to Hide)", 
            "visible": true, 
            "hoverinfo": "x+y+name", 
            "y": [
                "Cat Population", 
                "5565.00", 
                "7118.00", 
                "4375.00", 
                "4261.00", 
                "3786.00", 
                "2220.00", 
                "3544.00", 
                "2162.00", 
                "2453.00", 
                "1749.00", 
                "2420.00", 
                "1653.00", 
                "1438.00", 
                "1855.00", 
                "1912.00", 
                "1844.00", 
                "1349.00", 
                "1252.00", 
                "1191.00", 
                "1468.00", 
                "1041.00", 
                "1039.00", 
                "1510.00", 
                "877.00", 
                "810.00", 
                "1264.00", 
                "1185.00", 
                "1677.00", 
                "1593.00", 
                "668.00", 
                "731.00", 
                "533.00", 
                "628.00", 
                "805.00", 
                "625.00", 
                "796.00", 
                "455.00", 
                "514.00", 
                "393.00", 
                "498.00", 
                "277.00", 
                "290.00", 
                "309.00", 
                "187.00", 
                "212.00", 
                "234.00", 
                "174.00", 
                "144.00", 
                "63.00"
            ], 
            "x": [
                "Location", 
                "Texas", 
                "California", 
                "Florida", 
                "New York", 
                "Ohio", 
                "North Carolina", 
                "Pennsylvania", 
                "Georgia", 
                "Illinois", 
                "Tennessee", 
                "Michigan", 
                "Missouri", 
                "Arizona", 
                "Virginia", 
                "Indiana", 
                "Washington", 
                "Kentucky", 
                "Alabama", 
                "Colorado", 
                "New Jersey", 
                "Oklahoma", 
                "South Carolina", 
                "Wisconsin", 
                "Louisiana", 
                "Arkansas", 
                "Minnesota", 
                "Oregon", 
                "Maryland", 
                "Massachusetts", 
                "Mississippi", 
                "Kansas", 
                "New Mexico", 
                "West Virginia", 
                "Iowa", 
                "Nevada", 
                "Connecticut", 
                "Utah", 
                "Nebraska", 
                "Idaho", 
                "Maine", 
                "Montana", 
                "South Dakota", 
                "New Hampshire", 
                "Delaware", 
                "Rhode Island", 
                "Vermont", 
                "North Dakota", 
                "Wyoming", 
                "District of Columbia"
            ], 
            "type": "bar", 
            "autobiny": true
        }
    ]
}