var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "yaxis": {
            "range": [
                0, 
                7741.030594617732
            ], 
            "type": "linear", 
            "autorange": true, 
            "title": "Number of Pet Households (in 1000)"
        }, 
        "title": "Number of Pet Households  in US", 
        "breakpoints": [], 
        "xaxis": {
            "range": [
                -0.5, 
                49.5
            ], 
            "type": "category", 
            "autorange": true, 
            "title": "Location"
        }, 
        "hovermode": "closest", 
        "annotations": [
            {
                "xref": "x", 
                "arrowhead": 1, 
                "yref": "y", 
                "text": "California: 6,856&nbsp;", 
                "ay": -30, 
                "ax": 93, 
                "y": 6920.319235764282, 
                "x": 1.3053571428571435, 
                "showarrow": true
            }, 
            {
                "xref": "x", 
                "yref": "y", 
                "text": "Texas: 5,265", 
                "ay": -19, 
                "ax": 94, 
                "y": 5349.8221910447155, 
                "x": 2.5375, 
                "showarrow": true
            }, 
            {
                "xref": "x", 
                "yref": "y", 
                "text": "Florida: 4,138", 
                "ay": -21, 
                "ax": 119, 
                "y": 4133.953511261826, 
                "x": 3.6666666666666665, 
                "showarrow": true
            }
        ]
    }, 
    "data": [
        {
            "autobinx": true, 
            "uid": "855dc7", 
            "ysrc": "aircar:6:1ae682", 
            "xsrc": "aircar:6:3c77ff", 
            "name": "Column 1", 
            "mode": "markers", 
            "y": [
                "Number of Pet Households (in 1000)", 
                "6865.00", 
                "5265.00", 
                "4138.00", 
                "3802.00", 
                "2942.00", 
                "2677.00", 
                "2602.00", 
                "2108.00", 
                "2093.00", 
                "2089.00", 
                "1649.00", 
                "1611.00", 
                "1611.00", 
                "1540.00", 
                "1534.00", 
                "1497.00", 
                "1484.00", 
                "1352.00", 
                "1318.00", 
                "1217.00", 
                "1146.00", 
                "1134.00", 
                "1094.00", 
                "1088.00", 
                "957.00", 
                "951.00", 
                "937.00", 
                "872.00", 
                "728.00", 
                "716.00", 
                "691.00", 
                "654.00", 
                "629.00", 
                "548.00", 
                "523.00", 
                "476.00", 
                "475.00", 
                "364.00", 
                "352.00", 
                "345.00", 
                "289.00", 
                "251.00", 
                "230.00", 
                "219.00", 
                "189.00", 
                "188.00", 
                "147.00", 
                "137.00", 
                "63.00"
            ], 
            "x": [
                "Location", 
                "California", 
                "Texas", 
                "Florida", 
                "New York", 
                "Pennsylvania", 
                "Ohio", 
                "Illinois", 
                "Michigan", 
                "Georgia", 
                "North Carolina", 
                "Washington", 
                "New Jersey", 
                "Virginia", 
                "Tennessee", 
                "Missouri", 
                "Arizona", 
                "Indiana", 
                "Wisconsin", 
                "Massachusetts", 
                "Colorado", 
                "Minnesota", 
                "Maryland", 
                "Kentucky", 
                "Alabama", 
                "Oregon", 
                "South Carolina", 
                "Louisiana", 
                "Oklahoma", 
                "Connecticut", 
                "Arkansas", 
                "Kansas", 
                "Iowa", 
                "Mississippi", 
                "Nevada", 
                "New Mexico", 
                "Utah", 
                "West Virginia", 
                "Nebraska", 
                "Idaho", 
                "Maine", 
                "New Hampshire", 
                "Montana", 
                "Rhode Island", 
                "South Dakota", 
                "Delaware", 
                "Vermont", 
                "North Dakota", 
                "Wyoming", 
                "District of Columbia"
            ], 
            "type": "bar", 
            "autobiny": true
        }
    ]
}