var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "title": "Second Highest Number of Pet Hoursehoulds -- Texas", 
        "showlegend": false, 
        "breakpoints": [], 
        "hovermode": "closest", 
        "geo": {
            "scope": "usa"
        }, 
        "annotations": [
            {
                "xref": "x", 
                "yref": "y", 
                "text": "Texas", 
                "ay": 10, 
                "ax": 72, 
                "y": 0.10732984293193715, 
                "x": 0.5113095238095239, 
                "font": {
                    "size": 23
                }, 
                "showarrow": true
            }
        ]
    }, 
    "data": [
        {
            "locationssrc": "aircar:17:48ea8e", 
            "zmax": 6865, 
            "uid": "37e842", 
            "colorscale": [
                [
                    0, 
                    "rgb(220,220,220)"
                ], 
                [
                    0.2, 
                    "rgb(245,195,157)"
                ], 
                [
                    0.4, 
                    "rgb(245,160,105)"
                ], 
                [
                    1, 
                    "rgb(178,10,28)"
                ]
            ], 
            "zsrc": "aircar:17:7bd53e", 
            "type": "choropleth", 
            "zmin": 63, 
            "locations": [
                "Location", 
                "C", 
                "TX", 
                "F", 
                "New York", 
                "Pennsylvania", 
                "Ohio", 
                "Illinois", 
                "Michigan", 
                "Georgia", 
                "North Carolina", 
                "Washington", 
                "New Jersey", 
                "Virginia", 
                "Tennessee", 
                "Missouri", 
                "Arizona", 
                "Indiana", 
                "Wisconsin", 
                "Massachusetts", 
                "Colorado", 
                "Minnesota", 
                "Maryland", 
                "Kentucky", 
                "Alabama", 
                "Oregon", 
                "South Carolina", 
                "Louisiana", 
                "Oklahoma", 
                "Connecticut", 
                "Arkansas", 
                "Kansas", 
                "Iowa", 
                "Mississippi", 
                "Nevada", 
                "New Mexico", 
                "Utah", 
                "West Virginia", 
                "Nebraska", 
                "Idaho", 
                "Maine", 
                "New Hampshire", 
                "Montana", 
                "Rhode Island", 
                "South Dakota", 
                "Delaware", 
                "Vermont", 
                "North Dakota", 
                "Wyoming", 
                "District of Columbia"
            ], 
            "name": "Column 1", 
            "mode": "markers", 
            "showscale": false, 
            "autobinx": true, 
            "z": [
                "Number of Pet Households (in 1000)", 
                "6865.00", 
                "5265.00", 
                "4138.00", 
                "3802.00", 
                "2942.00", 
                "2677.00", 
                "2602.00", 
                "2108.00", 
                "2093.00", 
                "2089.00", 
                "1649.00", 
                "1611.00", 
                "1611.00", 
                "1540.00", 
                "1534.00", 
                "1497.00", 
                "1484.00", 
                "1352.00", 
                "1318.00", 
                "1217.00", 
                "1146.00", 
                "1134.00", 
                "1094.00", 
                "1088.00", 
                "957.00", 
                "951.00", 
                "937.00", 
                "872.00", 
                "728.00", 
                "716.00", 
                "691.00", 
                "654.00", 
                "629.00", 
                "548.00", 
                "523.00", 
                "476.00", 
                "475.00", 
                "364.00", 
                "352.00", 
                "345.00", 
                "289.00", 
                "251.00", 
                "230.00", 
                "219.00", 
                "189.00", 
                "188.00", 
                "147.00", 
                "137.00", 
                "63.00"
            ], 
            "locationmode": "USA-states", 
            "zauto": true, 
            "autobiny": true
        }
    ]
}